// Code generated by bebopc-go; DO NOT EDIT.

package generated

type Test uint32

const (
	Test_Start Test = 1
	Test_End Test = 2
	Test_Middle Test = 3
	// Deprecated: who knows
	Test_Beginning Test = 4
)

