// Code generated by bebopc-go; DO NOT EDIT.

package generated

import (
	"math"
)

const (
	uint8const = 1
	uint16const = 1
	uint32const = 1
	uint64const = 1
	int8const = 1
	int16const = 1
	int32const = 1
	int64const = 1
	float32const = 1
	float64const = 1.5
	boolconst = true
	stringconst = "1"
	guidconst = "e2722bf7-022a-496a-9f01-7029d7d5563d"
)

var (
	float64infconst = math.Inf(1)
	float64ninfconst = math.Inf(-1)
	float64nanconst = math.NaN()
)

