// Code generated by bebopc-go; DO NOT EDIT.

package generated

type uint8Enum uint8

const (
	uint8Enum_uint8enum1 uint8Enum = 1
	uint8Enum_uint8enum2 uint8Enum = 255
)

type uint16Enum uint16

const (
	uint16Enum_uint16enum1 uint16Enum = 1
	uint16Enum_uint16enum2 uint16Enum = 65535
)

type uint32Enum uint32

const (
	uint32Enum_uint32enum1 uint32Enum = 1
	uint32Enum_uint32enum2 uint32Enum = 4294967295
)

type uint64Enum uint64

const (
	uint64Enum_uint64enum1 uint64Enum = 1
	uint64Enum_uint64enum2 uint64Enum = 18446744073709551615
)

type int16Enum int16

const (
	int16Enum_int16enum1 int16Enum = 1
	int16Enum_int16enum2 int16Enum = 32767
)

type int32Enum int32

const (
	int32Enum_int32enum1 int32Enum = 1
	int32Enum_int32enum2 int32Enum = 268435455
)

type int64Enum int64

const (
	int64Enum_int64enum1 int64Enum = 1
	int64Enum_int64enum2 int64Enum = 1152921504606846975
)

