// Code generated by bebopc-go; DO NOT EDIT.

package generated

type testFlags uint32

const (
	testFlags_None testFlags = 0
	testFlags_Read testFlags = 1
	testFlags_Write testFlags = 2
	testFlags_ReadWrite testFlags = 3
	testFlags_Complex testFlags = 19
)

type testFlags2 int64

const (
	testFlags2_None testFlags2 = 0
	testFlags2_Read testFlags2 = 1
	testFlags2_Write testFlags2 = 2
	testFlags2_ReadWrite testFlags2 = 3
	testFlags2_Complex testFlags2 = 19
)

