// Code generated by bebopc-go; DO NOT EDIT.

package generated

type testFlags uint32

const (
	testFlags_None testFlags = 0
	testFlags_Read testFlags = 1
	testFlags_Write testFlags = 2
	testFlags_ReadWrite testFlags = 3
	testFlags_Complex testFlags = 19
)

