// Code generated by bebopc-go; DO NOT EDIT.

package generated

type test uint32

const (
	test_Start test = 1
	test_End test = 2
	test_Middle test = 3
	// Deprecated: who knows
	test_Beginning test = 4
)

