// Code generated by bebopc-go; DO NOT EDIT.

package generated

type enumU8 uint8

const (
	enumU8_EnumU81 enumU8 = 1
	enumU8_EnumU82 enumU8 = 2
)

type enumByte byte

const (
	enumByte_EnumByte1 enumByte = 1
	enumByte_EnumByte2 enumByte = 2
)

type enumU16 uint16

const (
	enumU16_EnumU161 enumU16 = 1
	enumU16_EnumU162 enumU16 = 2
)

type enumU32 uint32

const (
	enumU32_EnumU321 enumU32 = 1
	enumU32_EnumU322 enumU32 = 2
)

type enumU64 uint64

const (
	enumU64_EnumU641 enumU64 = 1
	enumU64_EnumU642 enumU64 = 2
)

type enum16 int16

const (
	enum16_Enum161 enum16 = 1
	enum16_Enum162 enum16 = 2
)

type enum32 int32

const (
	enum32_Enum321 enum32 = 1
	enum32_Enum322 enum32 = 2
)

type enum64 int64

const (
	enum64_Enum641 enum64 = 1
	enum64_Enum642 enum64 = 2
)

