name: Go

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v ./...
        go get github.com/google/go-cmp/cmp
        go test -v ./testdata/generated
        go test -v ./internal/importgraph
        echo "These packages have no tests-- this line confirms they compile"  
        go test -v ./testdata/incompatible/...
        go test -v ./testdata/generated-private

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: "--disable-all -E misspell -E deadcode -E govet"
